sudo: false
dist: trusty

language: node_js

node_js:
  - "8"

cache:
  directories:
    - node_modules

git:
  submodules: false

install:
  - npm i -g yarn
  - npm i -g codecov

script:
  - yarn

after_success:
  - codecov

branches:
  only:
  - master
  - develop
  - next
